### ISSUE TITLE
unable to use IAM docker from outside ec2

### ISSUE THREAD

**Issue by Alexc0007** [swipely/iam-docker#33]
Hi , 
i was trying to use IAM docker from outside ec2...
(from inside ec2 everything was working fine)

when i configured it from outside ec2 i encountered the following error on the docker running aws-cli commands:
Unable to locate credentials. You can configure credentials by running "aws configure".

when i started iam docker i used the following run command:
sudo docker run -e AWS_ACCESS_KEY_ID='ACCESS KEY' -e AWS_SECRET_ACCESS_KEY='SECRET KEY' --volume /var/run/docker.sock:/varun/docker.sock --restart=always --net=host IAM_DOCKER_IMAGE -listen-addr=0.0.0.0:9999

i configured iptables as required on the documentation to forward the request to the iam-docker.

in order to debug the issue i started watching the traffic coming from the aws-cli docker.
its being correctly redirected to the iam-docker.

inside the iam docker i can see that credentials are loaded correctly:
2019-07-29T08:56:09Z [iam] Checking for stale credential arn=MY_ROLE
2019-07-29T08:56:09Z [iam] Credential is fresh arn=MY_ROLE
2019-07-29T08:56:09Z [iam] Done refreshing all IAM credentials

then i decided to execute tcp dump inside iam-docker to see what is happening there , and i can see that its unable to reach aws metadata url:
08:38:35.398839 IP 172.17.0.2.48848 > 169.254.169.254.80: Flags [S], seq 2662688784, win 29200, options [mss 1460,sackOK,TS val 17010679 ecr 0,nop,wscale 7], length 0
08:38:35.398959 IP 169.254.169.254 > 172.17.0.2: ICMP host 169.254.169.254 unreachable - admin prohibited, length 68

now my questions are:
1. why does it even try to go to fetch metadata if i provided AWS credentials to start with?

2. why doesnt iam-docker show an error message without using tcpdump?
its hard to debug , i thought i have an issue getting from the aws-cli docker to iam-docker...
as it turned out that iam-docker is not responding correctly to aws-cli docker...

**Comment by nahiluhmot** [comment]
We rely on the AWS client library directly for the credential functionality. It was my understanding that the default instantiation would try to find credentials in the environment before reaching out to the metadata API. If this is not the case, I'd happily accept a pull request which adds that functionality, to include anything useful for debugging.

**Comment by Alexc0007** [comment]
Hi @nahiluhmot 
thanks for your reply.

go is not my strongest side but i can try to take a look at the code...
i thought maybe you would be familiar with the code part that handles the requests from the aws-cli docker...

do you maybe know anyone else who experienced the same behaviour?

**Comment by Alexc0007** [comment]
i tried to debug the issue a bit more and it seems like the iam-docker recognize the credentials when ever a request from the awscli docker comes but still it tries to contact aws metadata(which is impossible) and thats why it wont pass the credentials back to awscli...

in case when awscli is trying to identify itself with a role the credentials cant assume , iam-docker instantly recognize the situation and return access_denied to awscli.

still have to understand why iam-docker goes to aws metadata even though it has everything it needs to provide the correct credentials to awscli docker.

**Comment by Alexc0007** [comment]
apparently i had issues with local routings on my local computer where i tested the iam-docker...
when i installed it on a clear virtual machine - everything worked as expected.
closing this case.
